#!/usr/bin/env python3
"""Append P0 coverage gap test cases to suite 04 CSV."""

import os

csv_path = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "regression", "suites", "Frontend", "04-cart-checkout-tests.csv"
)

new_cases = [
    # GAP-001: Cart persistence (3 cases)
    'CART-040,Cart Persistence - Sign Out and Sign Back In,Cart > Persistence,Functional,Critical,5m,"User logged in with items in cart","1. Log in to storefront account\n2. Add 2-3 different products to cart with varying quantities\n3. Note all cart contents (products, quantities, prices)\n4. Sign out of the account\n5. Verify cart is cleared or inaccessible on storefront\n6. Sign back in with the same account\n7. Navigate to cart page\n8. Compare cart contents with noted items","- Cart contents are fully preserved after sign out/in cycle\n- All product names, quantities, and prices match pre-sign-out state\n- Cart count badge shows correct total\n- Cart subtotal matches pre-sign-out value\n- No duplicate items or missing items",Coverage Gap Analysis,Generated',

    'CART-041,Cart Merge - Guest to Authenticated User,Cart > Persistence,Functional,Critical,8m,"Registered account with existing items in cart (e.g. Product A qty 2); user currently signed out","1. As a guest (not signed in), add Product B to cart (qty 1)\n2. Add Product C to cart (qty 3)\n3. Verify guest cart shows Products B and C\n4. Sign in with the registered account (which already has Product A qty 2)\n5. Navigate to cart page\n6. Verify all items are present (Products A, B, and C)\n7. Verify quantities are correct (A=2, B=1, C=3)\n8. Verify no duplicate entries for any product","- Guest cart items merge with existing account cart\n- All items from both carts are present after login\n- Quantities from guest session are preserved\n- Pre-existing account cart items retain their quantities\n- Cart subtotal reflects combined items\n- No data loss from either cart source",Coverage Gap Analysis,Generated',

    'CART-042,Cart Persistence - Coupon Survives Sign Out/In,Cart > Persistence,Functional,Critical,6m,"User logged in, valid coupon code available, products in cart eligible for coupon","1. Log in and add eligible products to cart\n2. Apply a valid coupon code on the cart page\n3. Verify coupon is applied and discount is reflected in cart total\n4. Note the discount amount and final total\n5. Sign out of the account\n6. Sign back in with the same account\n7. Navigate to cart page\n8. Verify coupon is still applied\n9. Verify discount amount matches pre-sign-out value","- Coupon code persists across sign out/in cycle\n- Discount amount is identical after re-authentication\n- Cart total with discount matches pre-sign-out total\n- Coupon code is visible in cart summary\n- No need to re-enter the coupon code manually",Coverage Gap Analysis,Generated',

    # GAP-002: Price change during session (3 cases)
    'CART-043,Price Change During Session - Admin Increases Price,Cart > Price Changes,Functional,Critical,8m,"User logged in with item in cart at known price (e.g. $10.00), admin access available","1. Add a product to cart and note the displayed unit price ($10.00)\n2. Note the cart subtotal\n3. In Admin SPA, navigate to Catalog > Products > find the same product\n4. Update the product price to $15.00 and save\n5. Return to the storefront cart page\n6. Refresh the page (F5)\n7. Verify the displayed unit price for the line item\n8. Verify the cart subtotal has recalculated","- Cart line item price updates to $15.00 after refresh\n- Cart subtotal recalculates based on new price\n- Price change is reflected without requiring item removal and re-add\n- No stale cached price shown after refresh\n- Cart remains functional (can proceed to checkout at new price)",Coverage Gap Analysis,Generated',

    'CART-044,Price Change During Session - Price Drop With Indicator,Cart > Price Changes,Functional,High,8m,"User logged in with item in cart at known price, admin access available","1. Add a product to cart and note the price (e.g. $25.00)\n2. In Admin SPA, decrease the product price to $18.00\n3. Return to the storefront cart page\n4. Refresh the page\n5. Observe the price display for the line item\n6. Check for any price-change notification or indicator\n7. Verify the cart subtotal reflects the new price","- Cart shows the updated lower price ($18.00)\n- A visual indicator or notification informs the user that the price has changed (e.g. Price updated badge, strikethrough of old price, or toast notification)\n- Cart subtotal recalculates automatically\n- Customer benefits from the lower price\n- No confusion: old price is not prominently displayed without context",Coverage Gap Analysis,Generated',

    'CART-045,Item Goes Out of Stock While in Cart,Cart > Price Changes,Functional,Critical,8m,"User logged in with item in cart, admin access to adjust inventory","1. Add a product to cart (qty 1) and verify it appears in cart\n2. In Admin SPA, set the product inventory to 0 (out of stock)\n3. Wait for search index to update (30-60 seconds)\n4. Return to the storefront cart page\n5. Refresh the page\n6. Observe the status of the out-of-stock item in cart\n7. Attempt to click Proceed to Checkout","- Out-of-stock item is visually marked as unavailable in cart (grayed out, strikethrough, or badge)\n- Cart shows a clear message indicating the item is unavailable\n- Proceed to Checkout button is disabled or blocked with an error\n- User is prompted to remove the unavailable item before checkout\n- Other in-stock items in cart remain unaffected",Coverage Gap Analysis,Generated',

    # GAP-003: Cart validation errors block checkout (3 cases)
    'CART-046,Checkout Blocked by Out-of-Stock Item,Cart > Validation,Functional,Critical,5m,"User logged in, cart contains one out-of-stock item and one in-stock item","1. Navigate to cart page with mixed availability items\n2. Verify the out-of-stock item shows unavailable status\n3. Click Proceed to Checkout button\n4. Observe the validation behavior\n5. Remove the out-of-stock item from cart\n6. Click Proceed to Checkout again","- Checkout is blocked when cart contains out-of-stock items\n- Clear error message indicates which item(s) are unavailable\n- After removing unavailable item, checkout proceeds normally\n- In-stock items are not affected by the validation block\n- Error message is user-friendly and actionable",Coverage Gap Analysis,Generated',

    'CART-047,Cart Item Quantity Exceeds Available Stock,Cart > Validation,Functional,Critical,5m,"User logged in, product in cart, product has limited stock (e.g. 3 units)","1. Navigate to cart page\n2. Attempt to increase quantity beyond available stock (e.g. set to 10 when only 3 available)\n3. Observe validation behavior\n4. Check if quantity is capped or error is shown\n5. Attempt to proceed to checkout with over-stock quantity","- Validation error is displayed when quantity exceeds stock\n- Quantity is either capped at maximum available or an error message is shown\n- Error message clearly states the available stock limit\n- Cannot proceed to checkout with quantity exceeding stock\n- Cart subtotal reflects the valid (capped) quantity",Coverage Gap Analysis,Generated',

    'CART-048,Cart With Zero-Quantity Item Cannot Proceed to Checkout,Cart > Validation,Functional,Critical,5m,"User logged in, product in cart","1. Navigate to cart page\n2. Manually set item quantity to 0 using direct input (if allowed)\n3. Observe the cart behavior\n4. If item remains, attempt to click Proceed to Checkout\n5. Verify cart state after zero-quantity action","- Zero-quantity item is automatically removed from cart OR validation error is shown\n- If item is removed: cart updates immediately, cart count decrements, subtotal recalculates\n- If error is shown: clear message that quantity must be at least 1\n- Cannot proceed to checkout with zero-quantity items\n- Cart page shows empty state if last item is removed",Coverage Gap Analysis,Generated',

    # GAP-004: Guest checkout (4 cases)
    'CHK-061,Guest Checkout - Full Happy Path,Checkout > Guest,Functional,Critical,10m,"Guest user (not signed in), product available in catalog","1. Navigate to storefront without signing in\n2. Add a product to cart\n3. Click Proceed to Checkout\n4. Enter guest email address on checkout page\n5. Fill in all shipping address fields (name, street, city, state, zip, country, phone)\n6. Select a shipping method\n7. Enter payment details (Skyflow test card)\n8. Review order summary\n9. Click Place Order\n10. Verify order confirmation page","- Checkout flow completes without requiring account creation\n- Guest email is accepted and associated with the order\n- Shipping address is validated and accepted\n- Payment processes successfully\n- Order confirmation page displays with order number\n- Confirmation shows guest email, shipping address, and order total\n- Cart is cleared after successful order",Coverage Gap Analysis,Generated',

    'CHK-062,Guest Checkout - Invalid Email Validation and Recovery,Checkout > Guest,Functional,Critical,5m,"Guest user at checkout step","1. Proceed to checkout as guest\n2. Enter an invalid email format (e.g. notanemail)\n3. Attempt to proceed to next step\n4. Observe validation error\n5. Clear the field and enter another invalid format (e.g. user@)\n6. Attempt to proceed again\n7. Enter a valid email address (e.g. test@example.com)\n8. Proceed to next step","- Invalid email formats are rejected with clear validation error\n- Error message specifies the issue (e.g. Please enter a valid email address)\n- Validation triggers on submit attempt (not just on blur)\n- After entering valid email, user can proceed without issues\n- No residual error messages after correction\n- Previously entered valid data in other fields is preserved",Coverage Gap Analysis,Generated',

    'CHK-063,Guest Checkout - No Account Created,Checkout > Guest,Functional,Critical,5m,"Guest checkout just completed, order confirmation visible","1. Complete a full guest checkout (add item, checkout, pay, confirm)\n2. Note the guest email used and the order number\n3. Navigate to sign-in page\n4. Attempt to log in with the guest email and any password\n5. Observe login result\n6. Try Forgot Password with the guest email\n7. Observe the response","- Order confirmation shows the guest email, not an account username\n- No account is automatically created from guest checkout\n- Login attempt with guest email fails (account does not exist)\n- Forgot Password indicates no account found for that email\n- Guest order exists in Admin SPA under the guest email but without a registered account link",Coverage Gap Analysis,Generated',

    'CHK-064,Guest Checkout - Order History Requires Sign-In,Checkout > Guest,Functional,Critical,3m,"Guest checkout completed, on storefront","1. After guest checkout, attempt to navigate directly to /account/orders\n2. Observe the redirect behavior\n3. Attempt to navigate to /account\n4. Observe the redirect behavior","- Navigating to /account/orders redirects to sign-in page\n- Navigating to /account redirects to sign-in page\n- No order history is accessible without authentication\n- Sign-in page is displayed with option to create account or log in\n- No error page or broken state",Coverage Gap Analysis,Generated',

    # GAP-005: B2B checkout (3 cases)
    'CHK-065,B2B Checkout - PO Number Field,Checkout > B2B,Functional,High,8m,"B2B user logged in with company account, product in cart","1. Log in with B2B user credentials\n2. Add a product to cart\n3. Proceed to checkout\n4. Locate the PO (Purchase Order) number field\n5. Enter a PO number (e.g. PO-2026-001)\n6. Complete shipping and payment steps\n7. Place the order\n8. Verify order confirmation page shows PO number\n9. In Admin SPA, find the order and verify PO number is stored","- PO number field is present during B2B checkout\n- PO number is accepted and saved with the order\n- Order confirmation page displays the entered PO number\n- Admin SPA order detail shows the PO number\n- PO number persists in order history on storefront",Coverage Gap Analysis,Generated',

    'CHK-066,B2B Checkout - Order Pending Approval,Checkout > B2B,Functional,High,8m,"B2B buyer account that requires approval for orders, product in cart, B2B admin account available","1. Log in with B2B buyer account (requires approval)\n2. Add a product to cart\n3. Proceed through checkout (shipping, payment)\n4. Place the order\n5. Verify order status on confirmation page\n6. Navigate to order history\n7. Verify order status in order list","- Order is placed successfully but status shows Pending Approval (not Confirmed or Processing)\n- Order confirmation page clearly indicates approval is required\n- Order appears in order history with Pending Approval status\n- Order is not yet processed for fulfillment\n- Buyer receives notification that order is awaiting approval",Coverage Gap Analysis,Generated',

    'CHK-067,B2B Checkout - Admin Approves Pending Order,Checkout > B2B,Functional,High,8m,"B2B order in Pending Approval status, B2B admin account available, buyer account available","1. Log in with B2B admin account\n2. Navigate to pending orders or approval queue\n3. Find the pending order from the buyer\n4. Review order details\n5. Approve the order\n6. Verify order status changes\n7. Log out and log in with buyer account\n8. Navigate to order history\n9. Verify order status has changed from Pending Approval","- B2B admin can view and approve pending orders\n- Order status changes from Pending Approval to approved/processing status\n- Status change is reflected in order history\n- Buyer can see updated status on storefront\n- Approval workflow completes without errors",Coverage Gap Analysis,Generated',

    # GAP-006: Billing != shipping (3 cases)
    'CHK-068,Checkout - Different Billing and Shipping Addresses,Checkout > Address,Functional,High,8m,"User logged in with product in cart","1. Proceed to checkout\n2. Fill in shipping address fields\n3. Locate Billing same as shipping checkbox (should be checked by default)\n4. Uncheck the Billing same as shipping checkbox\n5. Verify separate billing address form appears\n6. Fill in different billing address fields (different street, city, state, zip)\n7. Complete payment and place order\n8. Verify order confirmation shows both addresses","- Billing same as shipping checkbox is present and checked by default\n- Unchecking reveals separate billing address form\n- Both addresses are independently validated\n- Order confirmation displays shipping address and billing address separately\n- Both addresses are correct and match entered values\n- Admin SPA order shows both distinct addresses",Coverage Gap Analysis,Generated',

    'CHK-069,Checkout - Order Confirmation Shows Both Addresses Correctly,Checkout > Address,Functional,High,5m,"Order just placed with different billing and shipping addresses","1. On order confirmation page, locate the shipping address section\n2. Verify all shipping address fields are correct\n3. Locate the billing address section\n4. Verify all billing address fields are correct\n5. Verify the two addresses are visually distinct and clearly labeled\n6. Navigate to order history and view the same order\n7. Verify both addresses are shown in order detail","- Shipping address section shows correct shipping details\n- Billing address section shows correct billing details\n- Addresses are clearly labeled (Shipping Address and Billing Address)\n- No address field mixing between shipping and billing\n- Order detail in order history also shows both addresses correctly\n- Labels and formatting are consistent",Coverage Gap Analysis,Generated',

    'CHK-070,Checkout - Invalid Billing Zip Code Validation,Checkout > Address,Functional,High,5m,"User at checkout with Billing same as shipping unchecked, billing form visible","1. Fill shipping address with valid data\n2. Uncheck Billing same as shipping\n3. Fill billing address with valid data except ZIP/postal code\n4. Enter invalid ZIP format (e.g. ZZZZZ or 123)\n5. Attempt to proceed or place order\n6. Observe validation error on billing ZIP field\n7. Correct the billing ZIP to a valid format\n8. Proceed with order placement","- Invalid billing ZIP triggers validation error\n- Error message is specific to the billing ZIP field (not generic)\n- Shipping address is not affected by billing validation error\n- After correcting ZIP, checkout proceeds normally\n- No data loss in other fields when fixing the error\n- Validation distinguishes between shipping and billing field errors",Coverage Gap Analysis,Generated',

    # GAP-007: Checkout field validation (4 cases)
    'CHK-071,Checkout - All Shipping Fields Empty Validation,Checkout > Validation,Functional,Critical,5m,"User logged in, product in cart, at checkout shipping step (no saved addresses or adding new address)","1. Navigate to checkout\n2. Leave all shipping address fields empty\n3. Click Continue or Next to proceed past shipping step\n4. Observe validation errors\n5. Count the number of error messages\n6. Verify each required field has an individual error indicator","- Per-field validation errors shown for each empty required field\n- Required fields include: first name, last name, address line 1, city, state/province, ZIP/postal code, country, phone\n- Each field shows its own error message (not just a single generic error)\n- Form does not advance to next step with empty fields\n- Focus moves to first invalid field (or errors are clearly visible)\n- No server-side error or page crash from empty submission",Coverage Gap Analysis,Generated',

    'CHK-072,Checkout - Invalid Phone Format Validation,Checkout > Validation,Functional,Critical,5m,"User at checkout shipping step","1. Fill all shipping fields with valid data except phone\n2. Enter invalid phone format (e.g. abc123)\n3. Attempt to proceed to next step\n4. Observe validation error on phone field\n5. Enter another invalid format (e.g. 12)\n6. Attempt again\n7. Enter valid phone number (e.g. +1 (555) 123-4567)\n8. Proceed to next step","- Invalid phone formats trigger validation error\n- Error message indicates the phone field specifically\n- Multiple invalid formats are all caught\n- After entering valid phone, checkout proceeds\n- Other valid field values are preserved during correction\n- No server-side error from malformed phone input",Coverage Gap Analysis,Generated',

    'CHK-073,Checkout - Invalid ZIP/Postal Code Validation,Checkout > Validation,Functional,Critical,5m,"User at checkout shipping step","1. Fill all shipping fields with valid data except ZIP/postal code\n2. Enter invalid ZIP (e.g. XXXXX or 1)\n3. Attempt to proceed to next step\n4. Observe validation error\n5. Enter valid ZIP for selected country\n6. Proceed to next step","- Invalid ZIP/postal code triggers field-specific validation error\n- Error message is clear (e.g. Please enter a valid ZIP/postal code)\n- Validation is appropriate for the selected country format\n- After correction, checkout proceeds to shipping method step\n- Other field values are preserved",Coverage Gap Analysis,Generated',

    'CHK-074,Checkout - Validation Error Recovery,Checkout > Validation,Functional,Critical,5m,"User at checkout with multiple validation errors showing","1. Submit checkout form with multiple invalid fields (empty name, invalid email, bad phone, invalid zip)\n2. Observe all validation errors displayed\n3. Fix the first error (enter valid name)\n4. Fix the second error (enter valid email)\n5. Fix the third error (enter valid phone)\n6. Fix the fourth error (enter valid ZIP)\n7. Resubmit the form\n8. Verify checkout proceeds to next step","- All validation errors are shown simultaneously on first submit\n- Fixing individual fields clears their respective error messages\n- No new spurious errors appear while fixing existing ones\n- After all errors are fixed, form submits successfully\n- Checkout proceeds to the next step normally\n- Previously valid fields retain their values throughout the correction process",Coverage Gap Analysis,Generated',

    # GAP-008: Reorder flow (3 cases)
    'ORD-001,Reorder - All Items Added to Cart at Current Prices,Orders > Reorder,Functional,High,8m,"User logged in with at least one completed order in order history, all ordered items still available","1. Navigate to order history (/account/orders)\n2. Find a completed order with multiple items\n3. Note the original order prices and quantities\n4. Click Reorder button on the order\n5. Verify redirect to cart page\n6. Compare cart items with original order items\n7. Verify quantities match original order\n8. Check that prices reflect current catalog prices (not historical order prices)","- All items from the original order are added to cart\n- Quantities match the original order\n- Prices reflect current catalog prices, not the historical order price\n- Cart subtotal is calculated using current prices\n- If current prices differ from original order, the new prices are shown\n- Success notification confirms items added to cart",Coverage Gap Analysis,Generated',

    'ORD-002,Reorder - Discontinued Item Handled Gracefully,Orders > Reorder,Functional,High,8m,"User logged in with completed order containing at least one discontinued/unavailable product and one available product","1. Navigate to order history\n2. Find an order that includes a now-discontinued product\n3. Click Reorder button\n4. Observe the cart page after reorder\n5. Check for warning messages about unavailable items\n6. Verify available items are still added to cart","- Available items from the order are added to cart successfully\n- Discontinued/unavailable item is NOT added to cart\n- Warning message clearly identifies which item(s) could not be added\n- Warning specifies the reason (e.g. Product X is no longer available)\n- Cart is still functional with the available items\n- User is not blocked from proceeding with available items only",Coverage Gap Analysis,Generated',

    'ORD-003,Reorder - Quantities Match Original Order,Orders > Reorder,Functional,High,5m,"User logged in with completed order containing items with various quantities (e.g. Product A qty 2, Product B qty 5)","1. Navigate to order history\n2. Open order detail for the target order\n3. Note quantities for each line item (e.g. A=2, B=5)\n4. Click Reorder\n5. Navigate to cart page\n6. Verify quantity for each item matches original order","- Product A quantity in cart = 2 (matches original order)\n- Product B quantity in cart = 5 (matches original order)\n- All line item quantities exactly match original order quantities\n- No items are added with default quantity of 1 instead of original quantity\n- Cart subtotal reflects correct quantities x current prices",Coverage Gap Analysis,Generated',

    # GAP-009: Order status tracking (3 cases)
    'ORD-004,Order Status - New Order Shows Correct Status,Orders > Status,Functional,High,5m,"User logged in, order just placed","1. Complete a checkout and place a new order\n2. Note the order number from confirmation page\n3. Navigate to order history (/account/orders)\n4. Find the newly placed order\n5. Click to view order detail\n6. Verify the order status displayed","- Newly placed order appears in order history\n- Order status shows New or equivalent initial status\n- Order detail page displays complete order information\n- Status is clearly visible and unambiguous\n- Order date matches current date",Coverage Gap Analysis,Generated',

    'ORD-005,Order Status - Admin Ships Order With Tracking,Orders > Status,Functional,High,10m,"Order in New status, admin access available, storefront user account that placed the order","1. In Admin SPA, navigate to Orders > find the target order\n2. Update order status to Shipped\n3. Add a tracking number (e.g. 1Z999AA10123456784)\n4. Save the changes\n5. Return to storefront, log in as the user who placed the order\n6. Navigate to order history\n7. Find the order and click to view detail\n8. Verify status and tracking information","- Order status on storefront updates to Shipped\n- Tracking number is displayed on order detail page\n- Tracking number is a clickable link (if carrier is recognized)\n- Status change is reflected in order history list view\n- Order detail shows complete shipment information\n- Previous status history may be visible (New -> Shipped)",Coverage Gap Analysis,Generated',

    'ORD-006,Order Status Filter - Filter by Shipped,Orders > Status,Functional,High,5m,"User logged in with multiple orders in different statuses (at least one Shipped and one in another status)","1. Navigate to order history (/account/orders)\n2. Locate the status filter or filter dropdown\n3. Select Shipped status filter\n4. Observe the filtered results\n5. Verify all displayed orders have Shipped status\n6. Clear the filter\n7. Verify all orders are shown again","- Status filter is available on order history page\n- Selecting Shipped filters list to show only shipped orders\n- No orders with other statuses appear in filtered results\n- Order count updates to reflect filtered results\n- Clearing filter restores full order list\n- Filter is responsive and does not cause page errors",Coverage Gap Analysis,Generated',
]

with open(csv_path, "a", encoding="utf-8") as f:
    f.write("\n")  # newline after existing content
    for case in new_cases:
        f.write(case + "\n")

print(f"Appended {len(new_cases)} test cases to {csv_path}")
